name: AntD Github actions workflow
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-to-github-pages:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install and Build
      run: |
        yarn
        yarn build
        echo $PATH
        pwd
        ls -la
      shell: bash
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build


